version: "3.8"

services:
  db:
    image: postgres:15
    container_name: strapi-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    image: strapi/strapi
    container_name: strapi-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: production
      APP_KEYS: someverylongrandomsecretkey
      API_TOKEN_SALT: sometokensalt
      ADMIN_JWT_SECRET: somejwtsecret
      JWT_SECRET: somejwtsecret
    ports:
      - "80:1337"
    networks:
      - strapi-net
    volumes:
      - ./strapi-app:/srv/app

volumes:
  db-data:
  strapi-app:

networks:
  strapi-net:
    driver: bridge
